### PR TITLE
Adds SQLTools for BigQuery

### PR DESCRIPTION
**Pull request by archiewood**

### CODE REVIEW

**Comment by archiewood** [comment]
Hey @iennae,

Apologies, I could have been clearer for this. 

[SQLTools](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools) is a widely used open source project with 3M installs of the VSCode extension, > 50 contributors, and [>1000 GH stars](https://github.com/mtxr/vscode-sqltools)

I recently contributed the BigQuery driver to this project, as we use BQ at work, and it didn't yet have a driver for SQLTools

The way the project is structured, each driver is a separate repo, and I included the think to the BQ specific driver, though it may have been more suitable to add the parent extension

If you still feel it's not an appropriate addition, that's fine, happy to leave this!

**Comment by iennae** [comment]
Thanks for the added context, let me revisit.

**Comment by archiewood** [comment]
Let me know if there's anything more you need here

**Review by tswast — APPROVED** [review]

**Comment by tswast** [comment]
Looks like we need to make some changes to the linter. Lot's of "Not compatible with your version of node/npm" errors.

**Review by rsamborski — APPROVED** [review]

**Pull request merged**
